name: "Black Duck Scan"
description: "Black Duck Scanning NEW VERSION for GitHub CI/CD Workflows"
author: "Matthew Brady"
branding:
  icon: 'shield'
  color: 'purple'
inputs:
  debug:
    description: "Debugging"
    default: "0"
    required: false
  url:
    description: "Black Duck URL"
    required: true
  token:
    description: "Black Duck API Token"
    required: true
  trustcert:
    description: "Trust Black Duck server certificate"
    default: "false"
    required: false
  project:
    description: "Project name in the Black Duck server"
    required: false
  version:
    description: "Project version name in the Black Duck server"
    required: false
  mode:
    description: "Scanning mode, intelligent or rapid"
    default: "rapid"
    required: false
  output:
    description: "Directory in which to save the rapid scan output"
    default: "blackduck-output"
    required: false
  fix_pr:
    description: "Generate a Fix PR for each insecure component"
    default: "false"
    required: false
  comment_on_pr:
    description: "Comment on a pull request"
    required: false
    default: "false"
  sarif:
    description: "Output file for SARIF"
    default: "blackduck-sarif.json"
    required: false
  incremental_results:
    description: "Incremental analysis"
    default: "false"
    required: false
  upgrade_major:
    description: "Recommend upgrade guidance to major, not just minor, versions"
    default: "true"
    required: false
  nocheck:
    description: "Skip check of GH commit/PR for changed package manager config files"
    default: "false"
    required: false
  detect_opts:
    description: "Passthrough options to Detect, comma delimited, exclude leading hyphens"
    required: false
  tool_version:
    description: "Version of external tool to use"
    required: true
  github_token:
    description: "GitHub Token"
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
